//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace Chat.Interaction.Xml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    [System.Xml.Serialization.XmlRootAttribute("ServerEnvelop", Namespace="ChatSvc", IsNullable=false)]
    public partial class ServerEnvelopType {
        
        private ServerEnvelopContentType itemField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ChatMessageInfo", typeof(ChatMessageInfoType))]
        [System.Xml.Serialization.XmlElementAttribute("ChatVoiceMessageData", typeof(ChatVoiceMessageDataType))]
        [System.Xml.Serialization.XmlElementAttribute("ClientProfileInfo", typeof(UserProfileInfoType))]
        [System.Xml.Serialization.XmlElementAttribute("Ok", typeof(OkType))]
        [System.Xml.Serialization.XmlElementAttribute("Pong", typeof(PingResponseType))]
        [System.Xml.Serialization.XmlElementAttribute("ServerError", typeof(ServerErrorInfoType))]
        public ServerEnvelopContentType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class ChatMessageInfoType : ServerEnvelopContentType {
        
        private UserProfileInfoType authorUserInfoField;
        
        private string textField;
        
        private long stampTicksField;
        
        /// <remarks/>
        public UserProfileInfoType AuthorUserInfo {
            get {
                return this.authorUserInfoField;
            }
            set {
                this.authorUserInfoField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long StampTicks {
            get {
                return this.stampTicksField;
            }
            set {
                this.stampTicksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class UserProfileInfoType : ServerEnvelopContentType {
        
        private string loginField;
        
        private bool isActivatedField;
        
        private bool isOnlineField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsActivated {
            get {
                return this.isActivatedField;
            }
            set {
                this.isActivatedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool IsOnline {
            get {
                return this.isOnlineField;
            }
            set {
                this.isOnlineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OkType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChatVoiceMessageDataType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChatMessageInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServerErrorInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserProfileInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public abstract partial class ServerEnvelopContentType {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResetPasswordSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangeEmailSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChangePasswordSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivateSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestActivationSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RegisterSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostVoiceMessageSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PostMessageSpecType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClientErrorInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PingRequestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StartChatSpecType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public abstract partial class ClientEnvelopContentType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class LoginSpecType : ClientEnvelopContentType {
        
        private string loginField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class ResetPasswordSpecType : ClientEnvelopContentType {
        
        private string loginField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class ChangeEmailSpecType : ClientEnvelopContentType {
        
        private string passwordField;
        
        private string oldEmailField;
        
        private string newEmailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OldEmail {
            get {
                return this.oldEmailField;
            }
            set {
                this.oldEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewEmail {
            get {
                return this.newEmailField;
            }
            set {
                this.newEmailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class ChangePasswordSpecType : ClientEnvelopContentType {
        
        private string newPasswordField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NewPassword {
            get {
                return this.newPasswordField;
            }
            set {
                this.newPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class ActivateSpecType : ClientEnvelopContentType {
        
        private string tokenField;
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class RequestActivationSpecType : ClientEnvelopContentType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class RegisterSpecType : ClientEnvelopContentType {
        
        private string loginField;
        
        private string passwordField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class PostVoiceMessageSpecType : ClientEnvelopContentType {
        
        private byte[] oggDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] OggData {
            get {
                return this.oggDataField;
            }
            set {
                this.oggDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class PostMessageSpecType : ClientEnvelopContentType {
        
        private string textField;
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class ClientErrorInfoType : ClientEnvelopContentType {
        
        private ErrorInfoType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorInfo")]
        public ErrorInfoType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtendedErrorInfoType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    [System.Xml.Serialization.XmlRootAttribute("ErrorInfo", Namespace="ChatSvc", IsNullable=false)]
    public partial class ErrorInfoType {
        
        private string messageField;
        
        private string stackTraceField;
        
        private StackItemInfoType[] stackDetailsField;
        
        private ErrorInfoType innerErrorField;
        
        private string typeNameField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("StackItem", IsNullable=false)]
        public StackItemInfoType[] StackDetails {
            get {
                return this.stackDetailsField;
            }
            set {
                this.stackDetailsField = value;
            }
        }
        
        /// <remarks/>
        public ErrorInfoType InnerError {
            get {
                return this.innerErrorField;
            }
            set {
                this.innerErrorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TypeName {
            get {
                return this.typeNameField;
            }
            set {
                this.typeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class StackItemInfoType {
        
        private SourceLocationInfoType locationField;
        
        private string methodSignatureField;
        
        /// <remarks/>
        public SourceLocationInfoType Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MethodSignature {
            get {
                return this.methodSignatureField;
            }
            set {
                this.methodSignatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class SourceLocationInfoType {
        
        private string fileNameField;
        
        private int lineField;
        
        private int columnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Line {
            get {
                return this.lineField;
            }
            set {
                this.lineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class PingRequestType : ClientEnvelopContentType {
        
        private long stampTicksField;
        
        /// <remarks/>
        public long StampTicks {
            get {
                return this.stampTicksField;
            }
            set {
                this.stampTicksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class StartChatSpecType : ClientEnvelopContentType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class OkType : ServerEnvelopContentType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class ChatVoiceMessageDataType : ServerEnvelopContentType {
        
        private UserProfileInfoType authorUserInfoField;
        
        private byte[] oggDataField;
        
        private long stampTicksField;
        
        /// <remarks/>
        public UserProfileInfoType AuthorUserInfo {
            get {
                return this.authorUserInfoField;
            }
            set {
                this.authorUserInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] OggData {
            get {
                return this.oggDataField;
            }
            set {
                this.oggDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long StampTicks {
            get {
                return this.stampTicksField;
            }
            set {
                this.stampTicksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class ServerErrorInfoType : ServerEnvelopContentType {
        
        private ErrorInfoType itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ErrorInfo")]
        public ErrorInfoType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    public partial class PingResponseType : ServerEnvelopContentType {
        
        private long requestStampTicksField;
        
        /// <remarks/>
        public long RequestStampTicks {
            get {
                return this.requestStampTicksField;
            }
            set {
                this.requestStampTicksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    [System.Xml.Serialization.XmlRootAttribute("ClientEnvelop", Namespace="ChatSvc", IsNullable=false)]
    public partial class ClientEnvelopType {
        
        private ClientEnvelopContentType itemField;
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActivateSpec", typeof(ActivateSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("ChangeEmailSpec", typeof(ChangeEmailSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("ChangePasswordSpec", typeof(ChangePasswordSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("ClientError", typeof(ClientErrorInfoType))]
        [System.Xml.Serialization.XmlElementAttribute("LoginSpec", typeof(LoginSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("Ping", typeof(PingRequestType))]
        [System.Xml.Serialization.XmlElementAttribute("PostMessageSpec", typeof(PostMessageSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("PostVoiceMessageSpec", typeof(PostVoiceMessageSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("RegisterSpec", typeof(RegisterSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("RequestActivationSpec", typeof(RequestActivationSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("ResetPasswordSpec", typeof(ResetPasswordSpecType))]
        [System.Xml.Serialization.XmlElementAttribute("StartChat", typeof(StartChatSpecType))]
        public ClientEnvelopContentType Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="ChatSvc")]
    [System.Xml.Serialization.XmlRootAttribute("ExtendedErrorInfo", Namespace="ChatSvc", IsNullable=false)]
    public partial class ExtendedErrorInfoType : ErrorInfoType {
        
        private string rawErrorInfoField;
        
        /// <remarks/>
        public string RawErrorInfo {
            get {
                return this.rawErrorInfoField;
            }
            set {
                this.rawErrorInfoField = value;
            }
        }
    }
}
